version: '3.8'

services:
  # Base de Datos (Para que no se borre nada)
  zabbix-db:
    image: mysql:8.0
    container_name: zabbix-db
    command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
    volumes:
      - ./zabbix_db_data:/var/lib/mysql
    env_file:
      - .env_db
    restart: always

  # Servidor Zabbix con Interfaz Web integrada (Appliance)
  zabbix-server:
    image: zabbix/zabbix-appliance:latest
    container_name: zabbix-server
    restart: always
    ports:
      - "9080:80"      # Web de Zabbix
      - "10052:10051"   # El puerto para tu IA (Trapper)
    volumes:
      - ./zabbix_export:/var/lib/zabbix/export
      - ./zabbix_snmptraps:/var/lib/zabbix/snmptraps
    environment:
      - PHP_TZ=Europe/Madrid
      - ZBX_STARTTRAPPERS=5 # Activamos los receptores para la IA
    depends_on:
      - zabbix-db

networks:
  default:
    driver: bridge
